services:
  terraform:
    image: hashicorp/terraform:1.9.0-rc3
    volumes:
        - ./setup:/tf/setup
        - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        # - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
        - TF_WORKSPACE=${TF_WORKSPACE}
        - AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"